---
- name: add username & password for FTS admin
  hosts: SHNCLVSGWs
  gather_facts: false
  connection: network_cli

  tasks:
    - name: add username & password 
      nxos_config:
       lines: 
         - "username {{ item }} password {{ item }}!234 priv-lvl 15"
      with_items: "{{ lookup('file', '/etc/ansible/shell/tier2_username.txt').splitlines() }}"

    - name: copy to startup-config
      nxos_config:
       lines:
         - copy running-config startup-config
