---
- name: Run local script
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: run local mkpasswd shell
      shell: bash /etc/ansible/shell/mkpasswd-Clvs@crdc.sh


- name: Change root password
  hosts: Linux
  gather_facts: false
  connection: ssh

  tasks:
    - name: Change Redhat root password
      user:
       name: root
       password: "{{ lookup('file', '/etc/ansible/Linux/Password/passwdhash.txt') }}"
