---
- name: Setup passwordless for linux
  hosts: test
  gather_facts: true
  connection: ssh

  tasks:
    - name: Create .ssh
      file:
        path: /root/.ssh
        owner: root
        group: root
        state: directory
        mode : '0700'
    
    - name: Create authorized_keys on remote server
      file:
        path: /root/.ssh/authorized_keys
        state: touch
        mode: '0640'
    
    - name: Copy pubkey to remote server
      authorized_key:
         user: root 
         key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

