- name: add vlan to vnic
  hosts: UCSM
  gather_facts: true
  connection: local

  tasks:
   - name: add vlan to vnic on Fabric A
     ucs_vnic_template:
        hostname: 10.124.113.4
        username: admin
        password: 1m0reTime
        name: LAB-Inter-LAN-A
        fabric: A
        vlans_list:
        - name: SMB-Private
        - name: test-ansible


